# CancellationException异常处理
	- ## 1、协程的取消需要内部配合（类似线程取消interrupt）
		- 1、在`while`中使用`isActive`作为判断条件判断协程是否活跃，跳出循环，协程执行结束
		- 2、while循环中使用协程提供的挂起函数比如delay等，当job.cancel时，挂起函数会抛出CancellationException取消异常，协程框架检测该异常会取消协程的
	- ## 2、当我们捕获`了CancellationException`时，要考虑是否要重新抛出。抛出才会取消协程。不抛出协程框架不会帮你取消协程的
		- 因为协程的结构化取消是依赖这个`CancellationException`的，最好不要捕获这个异常，即使捕获了，一般也不需要处理。
- # 其他异常处理
	- ## 4、**千万不要用`try-catch`直接包裹`launch`、`async`**。而这里正确的用法是把`try-catch`移到`launch`的代码块内部使用即可。
		- `launch`启动协程就像射箭，而包裹在`launch`外的`try-catch`只能捕获`launch`这个方法的异常，而对于其中的代码块的执行已经跳出了`try-catch`的作用域了。
	- ## 5、创建协程作用域时传入`SupervisiorJob`，可以控制异常传播的范围。
		- 比如Android中的`ViewModelScope`就使用了`SupervisiorJob`，即使该`Job`的子`Job`发生异常，也不会导致应用的其他功能出现问题。
	- ## 6、可以使用`CoroutineExceptionHandler`在顶层协程兜底处理异常，业务细节的代码异常处理还得用`try-catch`。
-